# -*- coding: utf-8 -*-
################################################################################################################################
#                       Project Euler Problem 44 Solution
#                               By Mike Kane
#
#Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are
#
#1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
#
#It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
#
#Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
#
################################################################################################################################
import time
pentNumList = []

def generatePentNumbers(number):
    return (number**2 * 3 - number)/2
    
def getAnswer():
    pentSet = set()
    number = 0
    pentNum = 0
    while True:
        number += 1
        pentNum = generatePentNumbers(number)
        pentSet.add(pentNum)
        print pentNum
        for x in pentSet:
            if pentNum-x in pentSet and pentNum-2*x in pentSet:
                return pentNum-2*x


        
        

        

        